# Generated by Django 3.0.6 on 2020-05-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField(default=1)),
                ('booked', models.BooleanField(default=False)),
                ('reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
    ]
