# Generated by Django 3.0.6 on 2020-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
