# Generated by Django 3.0.6 on 2020-05-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0002_auto_20200511_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='parked_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
